#!/bin/bash

########################################
# DAFS UPP PRODUCT GENERATION
########################################

date
export PS4='$SECONDS + '
set -x

####################################
# make temp directory
####################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
rm -rf "$DATA"
mkdir -p "${DATA}" && cd "${DATA}"

###########################################
# Run setpdy and initialize PDY variables
###########################################
export cycle=${cycle:-"t${cyc}z"}
setpdy.sh
. ./PDY

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
####################################
export SENDCOM=${SENDCOM:-"YES"}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-dafs}
export RUN=${RUN:-dafs}

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-/lfs/h1/ops/prod/com/hrrr/${hrrr_ver}/nwges/hrrrges_sfc/conus}
export COMOUT=${COMOUT:-$(compath.py -o "${NET}/${dafs_ver}")"/${RUN}.${PDY}/${cyc}/upp/conus"}
mkdir -p "${COMOUT}"

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

####################################
# Specify Execution Areas
####################################
export EXECdafs="${HOMEdafs}/exec"
export PARMdafs="${HOMEdafs}/parm"
export FIXdafs="${HOMEdafs}/fix"
export USHdafs="${HOMEdafs}/ush"

#########################################################
# print current environment
#########################################################
env

#########################################################
# Execute the Script
#########################################################
# Run UPP with 1 thread
export OMP_NUM_THREADS=1

"${HOMEdafs}/scripts/exdafs_upp_conus.sh"
export err=$?
err_chk

if [[ -e "${pgmout}" ]]; then
  cat "${pgmout}"
fi

##############################
# Remove the Temporary working directory
##############################
if [[ "${KEEPDATA^^}" != "YES" ]]; then
  rm -rf "${DATA}"
fi

date
